language: node_js
node_js:
  - 14.15.3

# Pre-testing installs
install:
  - echo "installing dependencies..."
  - npm install
  - echo "dependencies installed"

# Scripts to be run such as tests
before_script:
  - echo "running build command..."
  - npm run-script build
  - echo "build completed"

deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "meddy672-interview-coding-challenge"
  local_dir: build
  skip_cleanup: true

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "Deployment successful"